### ISSUE TITLE
Documentation Clarifications

### ISSUE THREAD

**Issue by shigadeyo** [cp2004/OctoPrint-OneDrive-Backup#109]
Below are a couple items that may be helpful to include in the documentation either inline or in a FAQ/Troubleshooting section:

- If the request code expires while trying to Add Account, restart OctoPrint, access the OneDrive Backup plugin, and then click the Add Account button again to generate a new request code
- After adding an account, immediately clicking the Change Folder button may result in an error; restart OctoPrint, access the OnceDrive Backup plugin, and then try again

I can create a pull request with the above, but wanted to discuss it here first in case I was just doing something incorrectly. Also, it may be possible to add buttons for the above items to retry/refresh, but I haven't had a chance to dig into the actual code yet. Thanks for the plugin and take care!

**Comment by cp2004** [comment]
> After adding an account, immediately clicking the Change Folder button may result in an error; restart OctoPrint, access the OnceDrive Backup plugin, and then try again

This one might be a bug that needs to fixing 🤔. I will have to test tomorrow.

The code timeout one is definitely relevant & useful.

**Comment by cp2004** [comment]
The plugin will show the expiry time of the code, as well as an error if it expires without auth instead of the (broken) success message. There's also a 'Refresh' or 'Retry' button if an error is encountered, which might help with the occasional errors which would have needed a reload. Will be in next release.

**Comment by shigadeyo** [comment]
@cp2004 ... Thanks for the update. Take care!

**Comment by cp2004** [comment]
1.0.1 Released.
