### ISSUE TITLE
[Request]: Rescan-Button for Folders

### ISSUE THREAD

**Issue by scopion1745** [cp2004/OctoPrint-OneDrive-Backup#110]
Cheers!

_there IS the posibility i haven't seen the button. Maybe i'm just to stupid._

**But** a rescan-button for the OneDrive-Folders would be nice.
MAYBE even a button to create new folders?

How did i get to this point:
I linked my Octoprint instance with my OneDrive and noticed, that i should create a new folder for the Backups.
So i created the folder via OneDrive. But it did not show up until i relinked and rebootet my Octoprint-Instance.

**Comment by cp2004** [comment]
It should show up after a refresh of the OctoPrint page, or even just pressing back and then opening the folder again. It initially shows a cached view while the data is refreshed in the background. An actual refresh button would make it simpler/clearer and should be quite easy, I suspect this will be a common thing for people to go away and create a new folder to store backups.

I did also notice in some testing that it can take a minute for the new folders to show up on the OneDrive API. A refresh button would make this very clear though.

**Comment by scopion1745** [comment]
Wow. That's a fast response. Awesome, thanks.

**Comment by scopion1745** [comment]
![image](https://user-images.githubusercontent.com/46906104/148393330-60e96a62-9e35-4fff-8913-4eb890789bb4.png)

**Comment by cp2004** [comment]
I will leave this open or I will forget to add the refresh button 🙂

**Comment by InoSiX** [comment]
Hiya,

Thanks for the plugin. I have been thinking about possible worst cast scenarios lately and this was one of them (recovering from complete RPI failure). The interface is straight forward and easy to use.

I would also like to throw my hat in the ring for the refresh button. I haven't used OneDrive really at all. I made a new folder in my OneDrive specifically for this after installing your plugin. I couldn't find a way to get new folders after having done it ones already. Even closing the SETTINGS dialog and reopening doesn't allow rescan (or perform a rescan on it's own). 

I basically unlinked my account and relinked it to rescan.

**Comment by cp2004** [comment]
Refresh button is implemented for the next release of the plugin.

**Comment by cp2004** [comment]
1.0.1 released.
