### ISSUE TITLE
[Bug]: Uploading Notifications

### ISSUE THREAD

**Issue by scopion1745** [cp2004/OctoPrint-OneDrive-Backup#111]
### Description of the bug

When uploading a Backup to OneDrive it spams you the progress as notifications.

![image](https://user-images.githubusercontent.com/46906104/148393555-314058bd-5aae-41f0-ad88-1f332e10ce53.png)

Bug or Feature?
Anyway: kinda annoying ;)
There might be a better way to solve this. Maybe something like a progessbar in one notification?
Or two notifications one saying "Currently uploading" and one Saying "i'm done!" or "Error....."

### Plugin version

1.0.0.0

### OctoPrint version

Version 1.7.2

### OctoPrint logs

not provided

**Comment by cp2004** [comment]
It should be updating the existing notifications, not creating new ones. Something is interfering with this process...

https://github.com/cp2004/OctoPrint-OneDrive-Backup/blob/1e3f3d25f437bcc8c9d1e99fda9fa81a9812c708/octoprint_onedrive_backup/static/src/components/App.tsx#L69-L80

What other plugins etc. do you have installed? You didn't upload the OctoPrint logs to I can't take a look and try and reproduce 🙁

**Comment by scopion1745** [comment]
![image](https://user-images.githubusercontent.com/46906104/148402447-39e772ca-7fd5-4ae1-8a42-684be7753d93.png)
I reproduced the problem. Now it seems to update to marked Notification. and there are not quiet as much notifications
This time i've attached the log for you ;)
[octoprint.log](https://github.com/cp2004/OctoPrint-OneDrive-Backup/files/7822646/octoprint.log)

**Comment by scopion1745** [comment]
I think the Notifications still need a bit of love :)
i tried it one more time: now it's down to 4 Notifications, but no 100% / "i'm done" / error note.
![image](https://user-images.githubusercontent.com/46906104/148426823-b1497874-20e5-477e-af6b-9fb52256158c.png)

Log added.
[Updated Log](https://github.com/cp2004/OctoPrint-OneDrive-Backup/files/7823742/octoprint.1.log)

Also a list of my installed Plugins:
PLUGINS
Bed Visualizer
Druckerbenachrichtigungen
Exclude Region
Firmware Check
Firmware Updater
OctoApp
Octolapse
OneDrive Backup
PrintTimeGenius Plugin
Printerdialoge
Prusa Leveling Guide
Themeify
Virtual Printer
ipOnConnect

**Comment by cp2004** [comment]
Interesting that it sometimes works & updates the old notification, and sometimes doesn't, which makes it strange...
I'll dig into it and add some extra checks to make sure it's only created once, or see if there is a plugin combo that is interfering.

**Comment by cp2004** [comment]
I've pushed a possible fix - I was never able to reproduce it, but I've reduced the chances of it recreating the notifications. If you press close on the notification it won't keep creating new ones now. I think this check might have been slightly dodgy.

It will be in 1.0.1, going out shortly, if you want to give it a test.

**Comment by scopion1745** [comment]
Cheers!

i just updated the Plugin and tested it twice.
Works like a charm now!
Thanks a lot :)
