### ISSUE TITLE
[Request]: Steps Clarification & Scheduled backup

### ISSUE THREAD

**Issue by InoSiX** [cp2004/OctoPrint-OneDrive-Backup#114]
### What would you like implemented?

Great plugin. I really like how it handles everything automatically and hooks into the built in backup system. After installing it, I wasn't 100% certain how to perform the backup to OneDrive. I only had one option that I knew to backup the Octoprint and tried it. I saw the message informing me it was also updated to OneDrive. I wasn't certain this would happened and instead guessed. It may be worth a mention on the plugin manager page. Perhaps a button to navigate to that page? Or buttons on your plugin page to perform the backup from it directly?

Additionally, I would be great to add a function to perform the backup on a schedule. I am not sure if this is already supported natively in Octoprint. If it is, I am sure your plugin will catch the event and perform the upload. If so, disregard this idea.

**Comment by cp2004** [comment]
Thanks for the feedback. It's written small at the end of the guide to use OctoPrint's built in backup & restore functionality, but it's small and written within the sentence, so probably not easy to pick out if you didn't need to read the whole page.

For scheduling - you can use the [Backup Scheduler](https://plugins.octoprint.org/plugins/backupscheduler/) plugin, which will also work with this plugin.

**Comment by InoSiX** [comment]
Ahh, wasn't aware of the Backup Scheduler. That is a good solution. Thanks for pointing it out.
