### ISSUE TITLE
[Bug]: Installation fails with Octoprint 1.8.0 & Python 3.10.4 ... Due to Rust/MSAL versions ?

### ISSUE THREAD

**Issue by Lee1502** [cp2004/OctoPrint-OneDrive-Backup#161]
### Description of the bug

Installation fails with Octoprint 1.8.0 & Python 3.10.4 ... 
Due to Rust version ?  and/or MSAL error ?
Please see attached logs.

pi@raspberrypi:~ $ rustc --version
rustc 1.61.0 (fe5b13d68 2022-05-18)

 I have rust version 1.61.0 installed  (see command line response above),    yet the plugin log of the install (which fails) seems to show rust 1.30 being used,  consequently it shows this error in the log. 
2022-05-20 10:32:09,079 ! This package requires Rust >=1.41.0.
See the attached plugin log for more details.

Forgive me if this is a user error.  This is a great plugin which I'd like to be able to install and use again.

### Plugin version

1.0.1

### OctoPrint version

1.8.0

### OctoPrint logs

[plugin_pluginmanager_console(1).log](https://github.com/cp2004/OctoPrint-OneDrive-Backup/files/8738348/plugin_pluginmanager_console.1.log)
[octoprint(1).log](https://github.com/cp2004/OctoPrint-OneDrive-Backup/files/8738352/octoprint.1.log)

**Comment by cp2004** [comment]
What OS are you using, and presumably you are using a RPi?

The cryptography dependency of the MSAL library (Microsoft library that the plugin uses) is the one having issues.

You may be able to get around it using the wheel instead, but Python 3.10 is not a version that comes with an OS I recognize - let me know what it is and we should be able to get it using PiWheels.

**Comment by Lee1502** [comment]
Hi Charlie,  Thanks for your prompt review and response. 
Yes, I'm using the standard Raspberry Pi OS.
I've been stung previously with older versions of Python, so I manually downloaded the latest version from the Python website 

I downloaded directly to my pi using this command:  wget https://www.python.org/ftp/python/3.10.4/Python-3.10.4.tgz

I see there are old 3.9 stable versions of Python available, so if you recommend I take python back to an earlier version, I'd be happy to do this.

Thanks again mate, don't spend too much of your headspace on this, as I said, its probably a user error, with me jumping the gun to a higher Python version.    but I guess it does give you a heads up on requirements/issues at later versions.
Cheers Lee

**Comment by cp2004** [comment]
[PiWheels](https://www.piwheels.org/) provides wheels for the Python versions that come with the relevant RPi OS releases, as shown on the homepage. As a result, they don't support Python 3.10. That would be the easiest thing to use as precompiled wheels make your life a lot easier and cuts down on installation time for anything else like this as well (eg. numpy).

In theory it should work to build Cryptography on Python 3.10, with the rust compiler etc. but I am not sure on the exact way that it uses the rust compiler - I would agree you seem to have the right things installed. I do have cryptography pinned to a slightly earlier version as the build was breaking on PiWheels on newer versions at the time, but now it seems to be fixed - not sure what they did.

**Comment by Lee1502** [comment]
Hi Charlie, 

Issue resolved by going back from Python 3.10.4 to the latest stable 3.9 version, ie. Python 3.9.13
All installed cleanly with no issues,  I'm happily using your plugin again.
Thanks again, Lee
