### ISSUE TITLE
Problem to backup to ondrive

### ISSUE THREAD

**Issue by stonefox1958** [cp2004/OctoPrint-OneDrive-Backup#172]
I can not see subfolders in the list of folders in Onedrive?
![missing](https://user-images.githubusercontent.com/8201781/177113666-2578f95b-134f-41b0-bdbb-c8adf8892fa7.jpg)

**Comment by cp2004** [comment]
You have to click to open the folders:
![image](https://user-images.githubusercontent.com/31997505/177191030-0b519ffb-ef1f-4ef7-9b87-3d09ea4d3bb9.png)


https://user-images.githubusercontent.com/31997505/177198566-da64f54e-714a-451a-8276-27d8257d1326.mp4

**Comment by cp2004** [comment]
Hopefully the comment above resolved the issue for you @stonefox1958?

**Comment by cp2004** [comment]
Since I've had no response, I'm closing the issue. Please do get in contact again if you have any further questions.
