### ISSUE TITLE
[Bug]: Uploads only when Backup made manually

### ISSUE THREAD

**Issue by S7EN** [cp2004/OctoPrint-OneDrive-Backup#176]
### Description of the bug

I use the command line backup funktion "/home/pi/oprint/bin/octoprint plugins backup:backup" after a successful print but even after restarting the pi the plugin does not recognise the newly created backup. Only when i start a backup manually in the GUI.

### Plugin version

1.0.1

### OctoPrint version

1.8.1

### OctoPrint logs

[octoprint (2).log](https://github.com/cp2004/OctoPrint-OneDrive-Backup/files/9174059/octoprint.2.log)

**Comment by cp2004** [comment]
The other plugins aren't loaded when you create a backup from the command line, so it's not possible for this plugin to react to that unfortunately.
